# Naive Bayes

# 1) GaussianNB

In [1]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split

os.chdir("../pydata")

# 이 자료는 컬럼의 이름이 없으므로 header=None
df = pd.read_csv('blob.csv', header=None)
print(df.head())
print("****************")
print(df.shape)                # (100, 3)

        0     1    2
0  0.9210 -9.98  0.0
1 -5.2700 -9.62  0.0
2 -0.4530 -6.04  0.0
3 -0.0856 -2.17  1.0
4  1.5300 -0.36  1.0
****************
(100, 3)


In [2]:
# 데이터 확인
X = df.iloc[:, 0:2]            # 독립변수가 두 개 있다 
y = df.iloc[:, 2]

print(X.head())
print("****************")
print(y.head())
print("****************")
print(X.shape)
print(y.shape)

        0     1
0  0.9210 -9.98
1 -5.2700 -9.62
2 -0.4530 -6.04
3 -0.0856 -2.17
4  1.5300 -0.36
****************
0    0.0
1    0.0
2    0.0
3    1.0
4    1.0
Name: 2, dtype: float64
****************
(100, 2)
(100,)


In [3]:
# 모델 생성, 훈련
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)
print(X_train.head())
print(y_train.head())

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X, y)

       0      1
80  0.48 -13.00
59 -0.36  -2.18
69  0.22 -10.10
68  1.59  -1.77
73  2.67  -1.70
80    0.0
59    1.0
69    0.0
68    1.0
73    1.0
Name: 2, dtype: float64


GaussianNB()

In [4]:
print("prediction:", gnb.predict(X_test))
print("훈련 데이터 점수:", gnb.score(X_train, y_train))
print("테스트 데이터 점수:", gnb.score(X_test, y_test))
print("테스트 데이터 점수(반올림):", round(gnb.score(X_test, y_test), 3))

prediction: [1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.
 0.]
훈련 데이터 점수: 1.0
테스트 데이터 점수: 1.0
테스트 데이터 점수(반올림): 1.0


# 2) BernoulliNB

In [5]:
import numpy as np

X = np.random.randint(2, size=(6, 100))
y = np.array([1, 2, 3, 4, 4, 5])

print(X)    # 0과 1로 구성된 100차원의 독립변수
print(y)

[[1 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1
  1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 1 1
  1 1 1 1 0 0 0 1 1 0 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1 1 0 1]
 [0 1 0 1 1 0 1 1 1 1 1 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1
  0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0 1 1
  0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1
  0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0]
 [1 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 0 0 1 0 0 1 1 1 0
  0 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 0 0 0 0 1
  0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0]
 [1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 1 1 0 1
  0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 1 1 0 0 1 1 0 1
  1 1 0 1 1 0 1 1 0 1 0 

In [6]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X, y)

BernoulliNB()

In [7]:
print("prediction:", bnb.predict(X))     # 간단한 연습을 위하여 훈련데이터를 테스트데이터로 다시 사용

prediction: [1 2 3 4 4 5]


# 3) MultinomialNB

In [8]:
from sklearn.feature_extraction import DictVectorizer

data = [{'house': 100, 'street': 50, 'shop': 25, 'car': 100, 'tree': 20},
        {'house': 5, 'street': 5, 'shop': 0, 'car': 10, 'tree': 500, 'river': 1}] 

dv = DictVectorizer(sparse=False)   # 순서에 상관없이 key와 value의 행렬을 구성
X = dv.fit_transform(data)
Y = np.array([1, 0])

print(X)

[[100. 100.   0.  25.  50.  20.]
 [ 10.   5.   1.   0.   5. 500.]]


In [9]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
mnb.fit(X, Y)

MultinomialNB()

In [10]:
X_test = data = [{'house': 80, 'street': 20, 'shop': 15, 'car': 70, 'tree': 10, 'river': 1},
                   {'house': 10, 'street': 5, 'shop': 1, 'car': 8, 'tree': 300, 'river': 0}]

mnb.predict(dv.fit_transform(X_test))

array([1, 0])